### ISSUE TITLE
Custom command options

### ISSUE THREAD

**Issue by HumanBot000** [crycode-de/ioBroker.discord#65]
It is possible to add custom command options for slash commands. I would really love to see this, for example to select a iobroker device.

**Comment by crycode-de** [comment]
Options for custom commands of type `text` can be defined as json string in the corresponding state `discord.0.slashCommands.<command-name>.option-<option-name>.choices`.
Example json: `[{"name": "Hof", "value": "hof"}, {"name": "Garten", "value": "garten"}]`

Since you have already closed this issue, I think you have already figured it out yourself. 🙂
